name: moppy-test-ci

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    name: linux-64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true

      - uses: actions/cache@v3
        with:
          path: '/moppy_env/'
          key: conda-${{ hashFiles('conda/environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Print cache hit
        run: echo ${{ steps.cache.outputs.cache-hit }}

      - name: Update environment
        run: mamba env update -n my-env -f conda/environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: install moppy
        shell: bash -l {0}
        run: pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: pytest
